User.create(email: 'danielallendeutsch@gmail.com', username: 'daniel', password: '12345678')
User.create(email: 'fish@gmail.com', username: 'fish', password: '12345678')

Book.create(title: 'Dear Katerina', user_id: 1, title_color: 'Fuchsia', featured: true)
Book.create(title: 'Mom in BK', user_id: 1, title_color: 'green', featured: true)
Book.create(title: 'Tim\'s Photos', user_id: 2, title_color: 'green', featured: true)
Book.create(title: 'My Trip To Israel', user_id: 1, title_color: 'green', featured: true)
Book.create(title: 'Life', user_id: 1, title_color: 'green', featured: true)
Book.create(title: 'The Snail and the Elephant', user_id: 1, title_color: 'green', featured: true)
Book.create(title: 'When We Were Young', user_id: 1, title_color: 'blue')
Book.create(title: 'Life As We Know It', user_id: 1, title_color: 'green', featured: true)
Book.create(title: 'Fortune', user_id: 1, title_color: 'blue')
Book.create(title: 'Writers Retreat', user_id: 1, title_color: 'blue')
Book.create(title: 'Fun in the Sun', user_id: 1, title_color: 'green', featured: true)

Page.create(book_id: 1, position: 1, flickr_photo_id: 16696250090, text: "dear katerina,\r\n\r\nin my email i wrote about the mistakes i made, and how certain things look to me now.  its really easy to focus on the most recent, when thinking about our relationship.  so i wanted to take a chance to look at the bigger picture--to remind us both of some things weve been through together, some places weve been, and who we are and were.")
Page.create(book_id: 1, position: 2, flickr_photo_id: 25676631612, text: 'most of the pictures are of you.  but this is one of us.  and i think it captures a lot.')
Page.create(book_id: 1, position: 3, flickr_photo_id: 16263752983, text: 'this photo and the next are two of my favorites.  i think they capture how i see you.  even when nothings going on, i saw how wonderful you are.')
Page.create(book_id: 1, position: 4, flickr_photo_id: 25758402895, text: 'i always loved looking at you in these moments.')
Page.create(book_id: 1, position: 5, flickr_photo_id: 25170998163, text: 'this is the first photo we ever took together.  which means it must be from ~7 years ago.  i remember wondering if i was crazy to visit you in ithaca.  excuse the eyebrow ring.')
Page.create(book_id: 1, position: 6, flickr_photo_id: 25170996403, text: 'do you remember when you took a crazy risk and visited me in israel?  this was my favorite day.  we bought falafels and took them into the aquarium.  we ate at the top of the tower, where we could see the red sea, egypt, and jordan.')
Page.create(book_id: 1, position: 7, flickr_photo_id: 25496935650, text: 'we went snorkeling after the aquarium.  youre wearing a necklace i gave you here.')
Page.create(book_id: 1, position: 8, flickr_photo_id: 25676638162, text: 'do you remember that summer we lived together in ithaca?  i think this is from then.')
Page.create(book_id: 1, position: 9, flickr_photo_id: 25702529601, text: 'we rented kayaks that summer.  you printed this photo for me, and i kept it on my desk when i worked at B&N.')
Page.create(book_id: 1, position: 10, flickr_photo_id: 16368966345, text: 'i love that we always did and tried new things.  this day didnt work out perfectly, but i i think we both had fun and felt good about ourselves.')
Page.create(book_id: 1, position: 11, flickr_photo_id: 17033510301, text: 'wine tasting was never a mistake.  and im glad we did it a bunch.')
Page.create(book_id: 1, position: 12, flickr_photo_id: 25702523481, text: 'the same goes for all the berry picking.  look at those fools making sure they didnt get sunburnt.')
Page.create(book_id: 1, position: 13, flickr_photo_id: 16882575422, text: 'you look like a badass here with your beer in texas.')
Page.create(book_id: 1, position: 14, flickr_photo_id: 16368913425, text: 'every day we spent exploring brooklyn was a good day to me.')
Page.create(book_id: 1, position: 15, flickr_photo_id: 19838801085, text: 'this was a really nice mothers day.  three generations of women!')
Page.create(book_id: 1, position: 16, flickr_photo_id: 19652190409, text: 'your family was always kind to include me.')
Page.create(book_id: 1, position: 17, flickr_photo_id: 16039483978, text: 'from a different day exploring at brooklyn bridge park.')
Page.create(book_id: 1, position: 18, flickr_photo_id: 16041213227, text: 'one of my favorite things about you is how adorable you are.  like here, with world-famous sniffy.')
Page.create(book_id: 1, position: 19, flickr_photo_id: 16039674090, text: 'and here!--at the farmers market.')
Page.create(book_id: 1, position: 20, flickr_photo_id: 19059391739, text: 'and here, at zion!')
Page.create(book_id: 1, position: 21, flickr_photo_id: 16845686763, text: 'and here, with some mad skillz in boston.')
Page.create(book_id: 1, position: 22, flickr_photo_id: 18630126513, text: 'and here, at bryce!')
Page.create(book_id: 1, position: 23, flickr_photo_id: 17465512461, text: 'and here, with the boats of beantown!')
Page.create(book_id: 1, position: 24, flickr_photo_id: 18630109573, text: 'and here, flexing in utah.')
Page.create(book_id: 1, position: 25, flickr_photo_id: 25820007356, text: 'and ESPECIALLY with dogs.')
Page.create(book_id: 1, position: 26, flickr_photo_id: 19254395451, text: 'i love going on adventures with you.')
Page.create(book_id: 1, position: 27, flickr_photo_id: 19592781035, text: 'sure, we could have done better. but weve explored some of the world together.')
Page.create(book_id: 1, position: 28, flickr_photo_id: 16414265263, text: 'and we did it in all sorts of styles.  like lovely airbnb stays.')
Page.create(book_id: 1, position: 29, flickr_photo_id: 19239619582, text: 'and also camping.  (i see you in there!)')
Page.create(book_id: 1, position: 30, flickr_photo_id: 25167116244, text: 'skiing every winter.')
Page.create(book_id: 1, position: 31, flickr_photo_id: 19063027440, text: 'searching for the queen.')
Page.create(book_id: 1, position: 32, flickr_photo_id: 19404810890, text: 'making it to the tops of mountains.')
Page.create(book_id: 1, position: 33, flickr_photo_id: 18623083304, text: 'planning the day with a smoothie.')
Page.create(book_id: 1, position: 34, flickr_photo_id: 19566597116, text: 'even our eating was adventurous.')
Page.create(book_id: 1, position: 35, flickr_photo_id: 19250627455, text: 'munchin on some breakfast.  i love this photo for how simple it all is.')
Page.create(book_id: 1, position: 36, flickr_photo_id: 18971875983, text: 'weve done lots of things together.')
Page.create(book_id: 1, position: 37, flickr_photo_id: 25702521731, text: 'and i really really like hiking together.  its my favorite thing.')
Page.create(book_id: 1, position: 38, flickr_photo_id: 19344021741, text: 'walking and talking all over.')
Page.create(book_id: 1, position: 39, flickr_photo_id: 25676633072, text: 'lots and lots of places.')
Page.create(book_id: 1, position: 40, flickr_photo_id: 25496925230, text: 'another of my favorites: TREATS with you.  like ice cream in puerto rico.')
Page.create(book_id: 1, position: 41, flickr_photo_id: 19340057025, text: 'and this wonderful pie in utah.')
Page.create(book_id: 1, position: 42, flickr_photo_id: 17279563819, text: 'and FISHHH is boston.')
Page.create(book_id: 1, position: 43, flickr_photo_id: 25135891634, text: 'AND THE TURTLE in ithaca.')
Page.create(book_id: 1, position: 44, flickr_photo_id: 19219498496, text: 'but my favorite thing of all is being silly with you.')
Page.create(book_id: 1, position: 45, flickr_photo_id: 19592772165, text: 'like when we found the buffalo.')
Page.create(book_id: 1, position: 46, flickr_photo_id: 16413689243, text: 'and when we found sniffing that was free!')
Page.create(book_id: 1, position: 47, flickr_photo_id: 16846665828, text: 'and when we do model-style photo shoots.  look at that smize.')
Page.create(book_id: 1, position: 48, flickr_photo_id: 25739946746, text: 'and when we play with sparklers.')
Page.create(book_id: 1, position: 49, flickr_photo_id: 19063081730, text: 'sometimes even in the middle of a hike.')
Page.create(book_id: 1, position: 50, flickr_photo_id: 25676627022, text: 'we tried to make a make rap album cover in chi-town.')
Page.create(book_id: 1, position: 51, flickr_photo_id: 25702526201, text: 'silly at the kids museum on another continent.')
Page.create(book_id: 1, position: 52, flickr_photo_id: 17278270980, text: 'imitating our adolescent selves.')
Page.create(book_id: 1, position: 53, flickr_photo_id: 17439801476, text: 'discovering Deep Dish Waddles!')
Page.create(book_id: 1, position: 54, flickr_photo_id: 25167117884, text: 'and the FUNKY CHICKEN in puerto rico.')
Page.create(book_id: 1, position: 55, flickr_photo_id: 19333970072, text: 'the funky chicken in the desert.')
Page.create(book_id: 1, position: 56, flickr_photo_id: 18630140803, text: 'the funky chicken everywhere, really.')
Page.create(book_id: 1, position: 57, flickr_photo_id: 25771538626, text: 'weve been through a lot of things together.')
Page.create(book_id: 1, position: 58, flickr_photo_id: 25170995543, text: 'including those starring roles in that james bond film.')
Page.create(book_id: 1, position: 59, flickr_photo_id: 25771541836, text: 'when we met, it was a long time ago.  i was unemployed and you were an undergrad.  we learned and and changed and grew a lot since then.')
Page.create(book_id: 1, position: 60, flickr_photo_id: 25170993863, text: 'weve explored a whole bunch too.')
Page.create(book_id: 1, position: 61, flickr_photo_id: 25820020396, text: 'weve even been known to do some dancing.')
Page.create(book_id: 1, position: 62, flickr_photo_id: 25725123842, text: 'and some rafting.')
Page.create(book_id: 1, position: 63, flickr_photo_id: 25702530041, text: 'do you remember exploring this cave outside of jerusalem?  we were ill-prepared in more ways then one, but had a great adventure.')
Page.create(book_id: 1, position: 64, flickr_photo_id: 19245560975, text: 'i love how brave you are.  there isnt a good picture, but i also love how smart you are.  there are lots of other things that i love.')
Page.create(book_id: 1, position: 65, flickr_photo_id: 25170985113, text: "we made each other so happy.\r\n\r\nand the real truth is, this isnt even half of it.  this isnt even ten percent.  what i happen to have photos of, doesnt begin to cover much.  weve done  and been through so much together.")
Page.create(book_id: 1, position: 66, flickr_photo_id: 25496925850, text: "i gave up, and i shouldnt have.  i think our story goes on longer than this.  i think these two people here can be us again.  if you want to try.\r\n\r\na final thing:  when you came to visit me in chicago, i walked you to the subway.  it was really early in the morning, so we were the only people out.  i swiped you in, and we waiting together for the train to come--me outside the gate and you inside.  the subway pulled up, and we quickly said our sad goodbye and kissed through the metal bars.  as your train pulled away, the conductor opened his window and shouted out to me: \"dont worry, ill get her there safe.\"  he must have seen how sad i was; i thought it was so kind of him to say something.\r\n\r\ni never told you that.  i thought it would make a nice anecdote at our wedding, and getting to surprise you with it then would be worth the price of storing it in secret for a few years.  i think about that often.")

Page.create(book_id: 2, position: 1, flickr_photo_id: '24133177795', text: 'this is a DELICIOUS bagel. that is suprisinly well priced.')
Page.create(book_id: 2, position: 2, flickr_photo_id: '23506296973', text: 'my mom pretending to drink coffee. in truth, she only likes the smell (not the taste) of coffee.')
Page.create(book_id: 2, position: 3, flickr_photo_id: '24024952152', text: 'cool statue in battery park.')
Page.create(book_id: 2, position: 4, flickr_photo_id: '24106913946', text: "view of Manhattan on the way to Staten Island. \n \n \n bar pop")
Page.create(book_id: 2, position: 5, flickr_photo_id: '24132974215', text: '')
Page.create(book_id: 2, position: 6, flickr_photo_id: '24106855456', text: '')
Page.create(book_id: 2, position: 7, flickr_photo_id: '23765143559', text: '')
Page.create(book_id: 2, position: 8, flickr_photo_id: '23765133139', text: '')
Page.create(book_id: 2, position: 9, flickr_photo_id: '23506073073', text: '')
Page.create(book_id: 2, position: 10, flickr_photo_id: '24106701506', text: '')
Page.create(book_id: 2, position: 11, flickr_photo_id: '24132712975', text: '')

Page.create(book_id: 3, position: 1, flickr_photo_id: '23928328272', text: 'we dont need no selfie stick.')
Page.create(book_id: 3, position: 2, flickr_photo_id: '23447514184', text: 'foo bar pop')
