User.create(email: 'danielallendeutsch@gmail.com', username: 'daniel', password: '12345678')
User.create(email: 'fish@gmail.com', username: 'fish', password: '12345678')

Book.create(title: 'Mom in BK', user_id: 1, featured: true)
Book.create(title: 'Tim\'s Photos', user_id: 1, featured: true)
Book.create(title: 'My Trip To Israel', user_id: 1, featured: true)
Book.create(title: 'Life', user_id: 1, featured: true)
Book.create(title: 'The Snail and the Elephant', user_id: 1, featured: true)
Book.create(title: 'When We Were Young', user_id: 1)
Book.create(title: 'Life As We Know It', user_id: 1, featured: true)
Book.create(title: 'Fortune', user_id: 1)
Book.create(title: 'Writers Retreat', user_id: 1)
Book.create(title: 'Fun in the Sun', user_id: 1, featured: true)

Page.create(book_id: 1, position: 1, flickr_photo_id: '24133177795', text: 'this is a DELICIOUS bagel. that is suprisinly well priced.')
Page.create(book_id: 1, position: 2, flickr_photo_id: '23506296973', text: 'my mom pretending to drink coffee. in truth, she only likes the smell (not the taste) of coffee.')
Page.create(book_id: 1, position: 3, flickr_photo_id: '24024952152', text: 'cool statue in battery park.')
Page.create(book_id: 1, position: 4, flickr_photo_id: '24106913946', text: "view of Manhattan on the way to Staten Island. \n \n \n bar pop")
Page.create(book_id: 1, position: 5, flickr_photo_id: '24132974215', text: '')
Page.create(book_id: 1, position: 6, flickr_photo_id: '24106855456', text: '')
Page.create(book_id: 1, position: 7, flickr_photo_id: '23765143559', text: '')
Page.create(book_id: 1, position: 8, flickr_photo_id: '23765133139', text: '')
Page.create(book_id: 1, position: 9, flickr_photo_id: '23506073073', text: '')
Page.create(book_id: 1, position: 10, flickr_photo_id: '24106701506', text: '')
Page.create(book_id: 1, position: 11, flickr_photo_id: '24132712975', text: '')

Page.create(book_id: 2, position: 1, flickr_photo_id: '23928328272', text: 'we dont need no selfie stick.')
Page.create(book_id: 2, position: 2, flickr_photo_id: '23447514184', text: 'foo bar pop')

Page.create(book_id: 3, position: 1, flickr_photo_id: '24386326185', text: "on october 12, 2009 i left the greater new york area on a flight to tel aviv, israel (connection via kiev, ukraine). i signed up for a five month work-study sort of program through oranim. i would work in a hotel four days a week in exchange for a place to live, food, flight, and an experience.")
Page.create(book_id: 3, position: 2, flickr_photo_id: '24018537199', text: "this is the deborah hotel in tel aviv. it is where all of the participants in my program met up on day 1. i did everything, as you will certainly come to notice, as cheaply as possible. exiting the airport is often the scariest part of being in a new place: you can no longer pretend like you aren't there and have no idea what you're doing.")
Page.create(book_id: 3, position: 3, flickr_photo_id: '24090727460', text: "this is a picture of me in front of the deborah, moments before my experience with the program officially began. \n \n i had high hopes of documenting every aspect of the journey. this did not happen. \n \n the program started with 56 participants. it was, thus, a bit overwhelming.")
Page.create(book_id: 3, position: 4, flickr_photo_id: '23758137664', text: "the first week of the program was spent touring around israel. the goals, i suspected, were two fold: see numerous areas of the country that is your birthright and get to know the other people on the program. \n \n this is us on the start of a hike.")
Page.create(book_id: 3, position: 5, flickr_photo_id: '24018537699', text: "this is us in the middle of a hike.")
Page.create(book_id: 3, position: 6, flickr_photo_id: '24278103852', text: "the hike led us to a small swimming hole. no one told us we might be swimming, but we went in in our underwear and/or clothes and it was nice.")
Page.create(book_id: 3, position: 7, flickr_photo_id: '24303844051', text: "this was our tour leader for the week. and he happened to be my tour leader for birthright. as both were through oranim, its not a huge coincidence. but it was a coincidence, and i was happy and excited to see him. ron is an excellent guide and a great guy, and he had a large part in my having such an amazing first experience in israel.")
Page.create(book_id: 3, position: 8, flickr_photo_id: '24386327295', text: "the next day we went to haifa. this shot overlooks the city.")
Page.create(book_id: 3, position: 9, flickr_photo_id: '23759522153', text: "haifa is most famous for the bahai gardens. bahai is a religion and this is their world center. \n \n i came back to haifa after the program was over and took a tour of the gardens, so there are more photos later.")
Page.create(book_id: 3, position: 10, flickr_photo_id: '24018538679', text: "we went on a lot of hikes during the first week, and here we are in the middle of another.")
Page.create(book_id: 3, position: 11, flickr_photo_id: '24360114596', text: "this time we were told that there would be swimming, so we came prepared.")
Page.create(book_id: 3, position: 12, flickr_photo_id: '23758139284', text: "the swimming hole was the base of a waterfall.")
Page.create(book_id: 3, position: 13, flickr_photo_id: '24360114996', text: "everyone who went in.")
Page.create(book_id: 3, position: 14, flickr_photo_id: '24303845471', text: "me. \n \n i don't actually have a six-pack, but because my hands are resting on my head it looks like i do. thats why this picture is included.")
Page.create(book_id: 3, position: 15, flickr_photo_id: '24278105212', text: "after the hike we went to tzfat. tzfat is known as the mystical city, and there does indeed feel like there's something in the air.")
Page.create(book_id: 3, position: 16, flickr_photo_id: '24018539709', text: "the bus stopped at this scenic viewpoint because it overlooks the city of jerusalem. i have this thing, i don't know why, of taking pictures of people taking pictures. maybe its because i feel like the person taking the pictures deserves to be in the picture. or maybe its because i want to take pictures of people that i know and this seems like a good time to take it. either way, you will find a bunch of these. \n \n taking the picture is my friend matt. and in the picture are shayna and trisha (from canada!).")
Page.create(book_id: 3, position: 17, flickr_photo_id: '23759523423', text: "matt posing. lindsey and erica on the right (from queens!).")
Page.create(book_id: 3, position: 18, flickr_photo_id: '24018539999', text: "jerusalem from above. the building with the gold hemisphere on top is dome of the rock--the holiest temple for muslims.")
Page.create(book_id: 3, position: 19, flickr_photo_id: '23759523683', text: "we then made our way into the old city of jerusalem. in the background is the dome of the rock. in front of that is the western wall (also known as the wailing wall). it is all that remains of the second temple.")
Page.create(book_id: 3, position: 20, flickr_photo_id: '24303846631', text: "before we got any closer to the wall we were given time to get lunch. this was, i believe, the first falafel of the trip i bought. a falafel ball is a friend ball of crushed chickpeas (or garbanzo beans). and the sandwich is made by packing those in a pita with tomatoes, cucumbers, onions, pickles, cabbage, fries and topped with tahini (the white sauce. it is made from sesame seeds). it can be made a variety of ways. \n \n its pretty damn good, filling, and usually costs less than 5 dollars. because of that, falafel was pretty much the only thing i would buy when i had to purchase a meal (most meals were provided by the hotels we worked for). \n i had so many falafels when i was there, though (literally over one hundred), that i stopped enjoying them and i have not had one since i left.")
